-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
